name: GitOps Push

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: environment
      ref:
        description: "Tag or GitHub SHA to deploy. Defaults to the branch that triggered the workflow"
        required: false
        type: string
        default: ''

permissions:
  contents: read

jobs:
  gitops-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: gitops-push
        uses: aisrael/gitops-push@main
        with:
          deployment: "sandbox"
          ref: ${{ github.sha }}
          token: ${{ secrets.GITOPS_PUSH_TOKEN }}
