name: GitOps Push

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: environment
      ref:
        description: "Tag or GitHub SHA to deploy. Defaults to the branch that triggered the workflow"
        required: false
        type: string
        default: ''

permissions:
  contents: read

jobs:
  gitops-push-dev:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: gitops-push-dev
        uses: aisrael/gitops-push@main
        with:
          deployment: sandbox
          environment: dev
          ref: ${{ github.ref_name }}
          gitops-repo-token: ${{ secrets.GITOPS_PUSH_TOKEN }}
  gitops-push-stage:
    if: ${{ github.event_name == 'push' }}
    needs: gitops-push-dev
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: gitops-push-stage
        uses: aisrael/gitops-push@main
        with:
          deployment: sandbox
          environment: stage
          ref: ${{ github.ref_name }}
          gitops-repo-token: ${{ secrets.GITOPS_PUSH_TOKEN }}

  gitops-push-workflow-dispatch:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: gitops-push-dev
        uses: aisrael/gitops-push@main
        with:
          deployment: sandbox
          environment: ${{ github.event.inputs.environment }}
          ref: ${{ github.event.inputs.ref }}
          gitops-repo-token: ${{ secrets.GITOPS_PUSH_TOKEN }}
