name: Test SemVer Check

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to check"
        required: true
        type: string
      prefix:
        description: "Prefix to check"
        required: false
        type: string

jobs:
  semver-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check version using aisrael/check-semver
        id: check-semver
        uses: aisrael/check-semver@first-try
        with:
          version: ${{ github.event.inputs.version }}
          prefix: ${{ github.event.inputs.prefix }}
          token: ${{ secrets.GITOPS_PUSH_TOKEN }}
      - name: Echo the output
        run: |
          echo "valid? ${{ steps.check-semver.outputs.valid }}"
