name: PR Comment
on:
  issue_comment:
    types: [created]

jobs:
  pr-comment:
    name: PR Comment
    runs-on: ubuntu-latest
    steps:
      - name: Github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo ::group::Github context
          echo $GITHUB_CONTEXT
          echo ::endgroup::
