name: Production Release

on:
  push:
    branches:
      - production

permissions:
  contents: read

jobs:
  gitops-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: gitops-push-dev
        uses: aisrael/gitops-push@main
        with:
          deployment: sandbox
          environment: production
          ref: ${{ github.sha }}
          gitops-repo-token: ${{ secrets.GITOPS_PUSH_TOKEN }}
