name: Production Release

on:
  push:
    branches:
      - production

permissions:
  contents: read

jobs:
  gitops-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need all tags
      - name: Determine latest tag
        id: latest-tag
        run: |
          latest_tag=$(git describe ${{ github.sha }})
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
      - name: gitops-push-dev
        uses: aisrael/gitops-push@main
        with:
          deployment: sandbox
          environment: production
          ref: ${{ steps.latest-tag.outputs.latest_tag }}
          gitops-repo-token: ${{ secrets.GITOPS_PUSH_TOKEN }}
